# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vincentguo/Code/mpenc_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vincentguo/Code/strongvelope

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vincentguo/Code/strongvelope/CMakeFiles /Users/vincentguo/Code/strongvelope/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vincentguo/Code/strongvelope/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named mpEnc_cpp

# Build rule for target.
mpEnc_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpEnc_cpp
.PHONY : mpEnc_cpp

# fast build rule for target.
mpEnc_cpp/fast:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/build
.PHONY : mpEnc_cpp/fast

src/aske.o: src/aske.cpp.o
.PHONY : src/aske.o

# target to build an object file
src/aske.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/aske.cpp.o
.PHONY : src/aske.cpp.o

src/aske.i: src/aske.cpp.i
.PHONY : src/aske.i

# target to preprocess a source file
src/aske.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/aske.cpp.i
.PHONY : src/aske.cpp.i

src/aske.s: src/aske.cpp.s
.PHONY : src/aske.s

# target to generate assembly for a file
src/aske.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/aske.cpp.s
.PHONY : src/aske.cpp.s

src/base64.o: src/base64.cpp.o
.PHONY : src/base64.o

# target to build an object file
src/base64.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/base64.cpp.o
.PHONY : src/base64.cpp.o

src/base64.i: src/base64.cpp.i
.PHONY : src/base64.i

# target to preprocess a source file
src/base64.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/base64.cpp.i
.PHONY : src/base64.cpp.i

src/base64.s: src/base64.cpp.s
.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/base64.cpp.s
.PHONY : src/base64.cpp.s

src/cliques.o: src/cliques.cpp.o
.PHONY : src/cliques.o

# target to build an object file
src/cliques.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/cliques.cpp.o
.PHONY : src/cliques.cpp.o

src/cliques.i: src/cliques.cpp.i
.PHONY : src/cliques.i

# target to preprocess a source file
src/cliques.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/cliques.cpp.i
.PHONY : src/cliques.cpp.i

src/cliques.s: src/cliques.cpp.s
.PHONY : src/cliques.s

# target to generate assembly for a file
src/cliques.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/cliques.cpp.s
.PHONY : src/cliques.cpp.s

src/codec_tlv.o: src/codec_tlv.cpp.o
.PHONY : src/codec_tlv.o

# target to build an object file
src/codec_tlv.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/codec_tlv.cpp.o
.PHONY : src/codec_tlv.cpp.o

src/codec_tlv.i: src/codec_tlv.cpp.i
.PHONY : src/codec_tlv.i

# target to preprocess a source file
src/codec_tlv.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/codec_tlv.cpp.i
.PHONY : src/codec_tlv.cpp.i

src/codec_tlv.s: src/codec_tlv.cpp.s
.PHONY : src/codec_tlv.s

# target to generate assembly for a file
src/codec_tlv.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/codec_tlv.cpp.s
.PHONY : src/codec_tlv.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/group_member.o: src/group_member.cpp.o
.PHONY : src/group_member.o

# target to build an object file
src/group_member.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/group_member.cpp.o
.PHONY : src/group_member.cpp.o

src/group_member.i: src/group_member.cpp.i
.PHONY : src/group_member.i

# target to preprocess a source file
src/group_member.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/group_member.cpp.i
.PHONY : src/group_member.cpp.i

src/group_member.s: src/group_member.cpp.s
.PHONY : src/group_member.s

# target to generate assembly for a file
src/group_member.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/group_member.cpp.s
.PHONY : src/group_member.cpp.s

src/handler.o: src/handler.cpp.o
.PHONY : src/handler.o

# target to build an object file
src/handler.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/handler.cpp.o
.PHONY : src/handler.cpp.o

src/handler.i: src/handler.cpp.i
.PHONY : src/handler.i

# target to preprocess a source file
src/handler.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/handler.cpp.i
.PHONY : src/handler.cpp.i

src/handler.s: src/handler.cpp.s
.PHONY : src/handler.s

# target to generate assembly for a file
src/handler.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/handler.cpp.s
.PHONY : src/handler.cpp.s

src/member.o: src/member.cpp.o
.PHONY : src/member.o

# target to build an object file
src/member.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/member.cpp.o
.PHONY : src/member.cpp.o

src/member.i: src/member.cpp.i
.PHONY : src/member.i

# target to preprocess a source file
src/member.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/member.cpp.i
.PHONY : src/member.cpp.i

src/member.s: src/member.cpp.s
.PHONY : src/member.s

# target to generate assembly for a file
src/member.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/member.cpp.s
.PHONY : src/member.cpp.s

src/message.o: src/message.cpp.o
.PHONY : src/message.o

# target to build an object file
src/message.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/message.cpp.o
.PHONY : src/message.cpp.o

src/message.i: src/message.cpp.i
.PHONY : src/message.i

# target to preprocess a source file
src/message.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/message.cpp.i
.PHONY : src/message.cpp.i

src/message.s: src/message.cpp.s
.PHONY : src/message.s

# target to generate assembly for a file
src/message.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/message.cpp.s
.PHONY : src/message.cpp.s

src/tlv.o: src/tlv.cpp.o
.PHONY : src/tlv.o

# target to build an object file
src/tlv.cpp.o:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/tlv.cpp.o
.PHONY : src/tlv.cpp.o

src/tlv.i: src/tlv.cpp.i
.PHONY : src/tlv.i

# target to preprocess a source file
src/tlv.cpp.i:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/tlv.cpp.i
.PHONY : src/tlv.cpp.i

src/tlv.s: src/tlv.cpp.s
.PHONY : src/tlv.s

# target to generate assembly for a file
src/tlv.cpp.s:
	$(MAKE) -f CMakeFiles/mpEnc_cpp.dir/build.make CMakeFiles/mpEnc_cpp.dir/src/tlv.cpp.s
.PHONY : src/tlv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... mpEnc_cpp"
	@echo "... src/aske.o"
	@echo "... src/aske.i"
	@echo "... src/aske.s"
	@echo "... src/base64.o"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/cliques.o"
	@echo "... src/cliques.i"
	@echo "... src/cliques.s"
	@echo "... src/codec_tlv.o"
	@echo "... src/codec_tlv.i"
	@echo "... src/codec_tlv.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/group_member.o"
	@echo "... src/group_member.i"
	@echo "... src/group_member.s"
	@echo "... src/handler.o"
	@echo "... src/handler.i"
	@echo "... src/handler.s"
	@echo "... src/member.o"
	@echo "... src/member.i"
	@echo "... src/member.s"
	@echo "... src/message.o"
	@echo "... src/message.i"
	@echo "... src/message.s"
	@echo "... src/tlv.o"
	@echo "... src/tlv.i"
	@echo "... src/tlv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

